spring:
  application:
    name: config-client
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
server:
  port: 8881
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
